### ISSUE TITLE
As a designer, I need to design the user interface for the game lobby and each game level to provide a consistent gaming experience.

### ISSUE THREAD

**Issue by StarrySkyYX** [113-1-DevOps/113-1-DevOps-Game-Student-Survival-Guide#12]
By creating visual sketches, I will help my teammates understand the design concept more effectively.

**Comment by Seveness1015** [comment]
可以點Branch查看圖檔，**此Branch無須合併**
圖檔資料夾內容/分層為：
>使用場景
　　素材（資料夾）
　　場景完整成現效果圖（.png）

素材的尺寸目前為直接參照效果圖的尺寸，若需要更大的圖檔請另外提出

**Comment by Seveness1015** [comment]
11/12更新：首頁、轉場、死亡頁
- 首頁：按鈕旁的提示字若不好排版可提出，可以直接將提示字與按鈕合併存為一張圖片
- 轉場：素材內另有一「狀態條」資料夾，內存放的是滿心／失敗一次／失敗兩次的進度條，可以直接根據剩餘生命抓取或是每條命單獨抓取（只是看能不能方便用的而已沒有強制也沒有特別的）
- 死亡頁：沒有什麼特別的

**Comment by Seveness1015** [comment]
[首頁,轉場,死亡頁.pdf](https://github.com/user-attachments/files/17707011/default.pdf)
PDF供參，有疑問請再提出

**Comment by Seveness1015** [comment]
**### 注：畫面皆以16:9設計！**

**Comment by Seveness1015** [comment]
[颱風天,車禍.pdf](https://github.com/user-attachments/files/17716234/default.pdf)
PDF供參，有疑問請再提出

**Comment by gut2003817** [comment]
嗨嗨嗨嗨嗨
有個問題，就是撞到障礙物就少一命然後結束生命，還是撞到少一命但可以繼續完成？
然後根據你之前的簡報，如果是像Subway Surfers，會有終點嗎？

**Comment by StarrySkyYX** [comment]
首頁的部分，幫我把除了按鈕以外的東西都存成一張圖片，謝謝!

**Comment by Seveness1015** [comment]
> 首頁的部分，幫我把除了按鈕以外的東西都存成一張圖片，謝謝!

好的等我一下我在吃豆花😋

**Comment by Seveness1015** [comment]
> 首頁的部分，幫我把除了按鈕以外的東西都存成一張圖片，謝謝!

圖片已合併完成並另外上傳，更新內容如下圖：
- 新增 " image " 資料夾，內部檔案皆以英文命名，為確定使用的檔案
- 原有的 " DevOps_素材 " 則作為第一版圖片進行預覽使用
![image](https://github.com/user-attachments/assets/2ceb0025-6447-4e5f-bfec-1b31473f74d6)

**Comment by Seveness1015** [comment]
11/15更新：
已上傳新版圖檔至此issue分支

frontpage
> background
> button [尺寸若需要調整請再次提出]

transition
> heart full [正常通關使用此轉場圖]
> button [對齊愛心，在畫面右邊]

failpage
> background
> button [在介面右下角]

typhoon
> background [需要循環]
> streeview [需要循環，左右不限]
> school [終點顯示]
> obstacle [減少至3項]
> player [左/右]
> button_umb [左/右]
> weathercock [左/右]
風向[左]，需要點按鈕[右]，玩家圖標顯示為[右]

car accident
> background [需要循環] **放錯了晚點更新**
> quantity [油量圖標] **放錯了晚點更新**
> school [終點出現]
> gas barrel [補充油量，隨機出現]
> car [障礙物，隨機出現]
> player [玩家]

hide from teacher 不單作背景，請直接呼叫圖片
> not moving [玩家不可動作]
> eating [完成偷吃任務]
> playing [完成偷玩任務]
> button_eating [偷吃任務按鈕，放在文字旁邊]
> button_playing [偷玩任務按鈕，放在文字旁邊]

**Comment by Seveness1015** [comment]
11/15更新：

typhoon
> background [**與街景合併，循環**]
> 
> school [終點顯示]
> obstacle [減少至3項]
> player [左/右]
> button_umb [左/右]
> weathercock [左/右]
> 風向[左]，需要點按鈕[右]，玩家圖標顯示為[右]

其他內容無更新

**Comment by StarrySkyYX** [comment]
確認已完成遊戲場景設計
