### ISSUE TITLE
As a Engineer, I need to record login failure counts by using OpenTelemetry to improve system observability.

### ISSUE THREAD

**Issue by StarrySkyYX** [113-1-DevOps/113-1-DevOps-Game-Student-Survival-Guide#42]

**Comment by isoqt08** [comment]
![Image](https://github.com/user-attachments/assets/68d073a8-f4f0-4fa5-9872-a4f5247cd09d)
![Image](https://github.com/user-attachments/assets/37f42855-e6b8-4939-a00a-0aca97e81c3e)
![Image](https://github.com/user-attachments/assets/d349f5f0-b2e9-479b-b4c1-d62828344c12)
![Image](https://github.com/user-attachments/assets/6b3145e9-49c4-47d0-aaac-86c0840a65a7)
