### ISSUE TITLE
As a designer, I need to design the user interface for the game lobby and each game level to provide a consistent gaming experience.

### ISSUE THREAD

**Issue by StarrySkyYX** [113-1-DevOps/113-1-DevOps-Game-Student-Survival-Guide#7]
By creating visual sketches and providing basic interface templates, I will help my teammates understand the design concept more effectively.

**Comment by Seveness1015** [comment]
[DevOps_01.pdf](https://github.com/user-attachments/files/17650499/DevOps_01.pdf)
"颱風天"那邊我寫了兩種方案，看負責的要不要更改，不然兩個模式會是一樣的
關卡介面（綠色）是我大概設想的UI畫面，可以再調整

**Comment by Seveness1015** [comment]
1107 /待補
- [ ] 五關關卡隨機循環，每完成一輪後下個循環將提升速度/縮短時間
- [ ] 關卡設定生命值，生命值耗盡則循環結束

**Comment by Seveness1015** [comment]
颱風天：
人（相對障礙物）靜止，靠左右Ａ/Ｄ躲避飛來的障礙物（動態）

**Comment by Seveness1015** [comment]
車禍：
人、障礙物皆為動態，前後左右Ｗ/Ａ/Ｓ/Ｄ躲避移動的障礙物（動態），障礙物有逆向/正向來的

**Comment by Seveness1015** [comment]
* 都是去學校

**Comment by Seveness1015** [comment]
讀書的誘惑：
加蚊子（點擊拍死）

**Comment by Seveness1015** [comment]
社團活動：
線太多了

**Comment by isoqt08** [comment]
颱風天方案目前想先往plan b試試看

**Comment by Seveness1015** [comment]
> 颱風天方案目前想先往plan b試試看

**颱風天是用這個方案** 芫榛🥺🥺
颱風天：
人（自動等速前進，相對障礙物）靜止，靠左右Ａ/Ｄ躲避飛來的障礙物（動態），障礙物（360）集中朝玩家飛來
風力機制：定時變向，需靠雨傘防禦
雨傘機制：控制傘朝向（滑鼠拖曳）需朝向風的吹向
沒有控制好傘的話人會被吹走，人會根據風向被改變座標，直到被障礙物擊落或時間結束前未到達目的地則視為失敗

**Comment by StarrySkyYX** [comment]
颱風天方案變成我是負責人
芫榛改成躲老師視線那個

**Comment by StarrySkyYX** [comment]
遊戲方案確認。

**Comment by Seveness1015** [comment]
補充更新上周四確認後的新配置介面：
![Image](https://github.com/user-attachments/assets/5edd925d-9ac9-490e-af04-bf890ee44770)
⬆️颱風天

![Image](https://github.com/user-attachments/assets/0410bab1-f0eb-46b7-9f61-9fbbb4f64adb)
⬆️車禍

![Image](https://github.com/user-attachments/assets/0e0cb3b7-199a-4463-84da-6ff8dd4d6534)
⬆️讀書

![Image](https://github.com/user-attachments/assets/a632ca3f-78db-4a0a-8c23-2079826e40d5)
⬆️社團（玩法更新為 節奏醫生 的方式）
